feat: fixed issues with adding file to target
customerio/customerio-expo-plugin pull request #10
Opened 2022-11-26 13:41 UTC by xtreem88

This PR fixes the issue with xcode not recognizing `PushNotification.swift` and requiring an extra step of adding the file after  `prebuild`

2022-11-26 13:41 UTC, xtreem88 commented
<!-- https://github.com/levibostian/cathy comment. id:action-semantic-pr_help-pr-title -->
**Pull request title looks good 👍!** 

If this pull request gets merged, **it will cause a new release** of the software. Example: If this project's latest release version is `1.0.0`. If this pull request gets merged in, the next release of this project will be `1.1.0`. This pull request **is not** a breaking change.

All merged pull requests will *eventually* get deployed. But some types of pull requests will trigger a deployment (such as features and bug fixes) while some pull requests will wait to get deployed until a later time. 

**To merge this pull request, add the label `Ready to merge` to this pull request and I'll merge it for you.**


<details >
<summary>This project uses a special format for pull requests titles. Expand this section to learn more (expand by clicking the ᐅ symbol on the left side of this sentence)...</summary>
<br>

This project uses a special format for pull requests titles. Don't worry, it's easy!

This pull request title should be in this format:

```
<type>: short description of change being made
```

**If your pull request [introduces breaking changes](https://web.archive.org/web/20220725195319/https://nordicapis.com/what-are-breaking-changes-and-how-do-you-avoid-them/)** to the code, use this format:

```
<type>!: short description of breaking change
```

where `<type>` is one of the following:

- `feat:` - A feature is being added or modified by this pull request. Use this if you made any changes to any of the features of the project.
- `fix:` - A bug is being fixed by this pull request. Use this if you made any fixes to bugs in the project. 

- `docs:` - This pull request is making documentation changes, only.
- `refactor:` - A change was made that doesn't fix a bug or add a feature.
- `test:` - Adds missing tests or fixes broken tests.
- `style:` - Changes that do not effect the code (whitespace, linting, formatting, semi-colons, etc)
- `perf:` - Changes improve performance of the code.

- `build:` - Changes to the build system (maven, npm, gulp, etc)
- `ci:` - Changes to the CI build system (Travis, GitHub Actions, Circle, etc)

- `chore:` - Other changes to project that don't modify source code or test files.
- `revert:` - Reverts a previous commit that was made.


### Examples:
```
feat: edit profile photo
refactor!: remove deprecated v1 endpoints
build: update npm dependencies
style: run formatter 
```

Need more examples? Want to learn more about this format? [Check out the official docs](https://www.conventionalcommits.org/).

**Note:** If your pull request does multiple things such as adding a feature _and_ makes changes to the CI server _and_ fixes some bugs then you might want to consider splitting this pull request up into multiple smaller pull requests.

</details>

2022-11-28 05:34 UTC, levibostian commented on src/ios/withNotificationsXcodeProject.ts
>    const projPath = `${iosPath}/${appName}.xcodeproj/project.pbxproj`;
The `xcodeproj` directory can have whatever name it wants, not necessarily `$appName`. 

Maybe query the file system to find the name of the directory instead "*.xcodeproj"?

2022-11-28 05:34 UTC, levibostian commented on src/ios/withNotificationsXcodeProject.ts
> +    `${iosPath}/${appName}/${filename}`;
The source code of the iOS app doesn't need to be `${iosPath}/${appName}/`. The directory can be named something completely different. 

Perhaps a more stable way to find the name of the source code directory is to query the file system for a directory that contains `Info.plist` file or some Swift/objective-c source code?

2022-11-28 05:34 UTC, levibostian commented on src/ios/withNotificationsXcodeProject.ts
> +    });
I believe this code is saying, "If the source code of the iOS app does not exist in the directory path `$iosPath/$appName`, create the directory". 

Do we want to do that? Force customers to store some source code in a random directory they may not want to use in their iOS app?

2022-11-28 05:45 UTC, levibostian commented on src/ios/withNotificationsXcodeProject.ts
> +  for (const key in configurations) {
I think that this code is iterating through all targets of the Xcode project and modifying the build settings for it. 

I don't think that's what we want to do. We only want to modify build settings for targets that we created.

2022-11-28 06:04 UTC, xtreem88 commented on src/ios/withNotificationsXcodeProject.ts
>    const projPath = `${iosPath}/${appName}.xcodeproj/project.pbxproj`;
`$appName` Is predefined in the config for any Expo RN project, these files are "generated" by Expo and usually have similar structures

2022-11-28 06:05 UTC, xtreem88 commented on src/ios/withNotificationsXcodeProject.ts
> +  for (const key in configurations) {
This is a target we have created

2022-11-28 06:14 UTC, xtreem88 commented on src/ios/withNotificationsXcodeProject.ts
> +    `${iosPath}/${appName}/${filename}`;
The aim here is to upload the file into a specific (predefined) directory, and it is expected that `${iosPath}/${appName}/` should exist

2022-11-28 06:18 UTC, xtreem88 commented on src/ios/withNotificationsXcodeProject.ts
> +    });
This path should exist; the idea here is if for any reason, this code runs before the directory is created, then we want to create it and drop the file in there.

2022-11-28 14:36 UTC, levibostian commented on src/ios/withNotificationsXcodeProject.ts
> +  for (const key in configurations) {
How so? From reading the code `xcodeProject.pbxXCBuildConfigurationSection()` it looks like it's getting the build configuration for the whole project instead of 1 individual target?

2022-11-28 14:36 UTC, levibostian commented on src/ios/withNotificationsXcodeProject.ts
> +    });
Is it a problem if the path does not exist? That is what my original comment is meant to ask.

2022-11-28 14:37 UTC, levibostian commented on src/ios/withNotificationsXcodeProject.ts
> +    `${iosPath}/${appName}/${filename}`;
Is it a problem if the path does not exist and the directory is named something other then `$appName`? That is what my original comment is meant to ask.

2022-11-28 14:39 UTC, levibostian commented on src/ios/withNotificationsXcodeProject.ts
>    const projPath = `${iosPath}/${appName}.xcodeproj/project.pbxproj`;
Ok. If the files are generated by Expo which means they have similar structure then, yes, we can assume that this is the naming pattern. 

If Expo didn't generate these files then I would say that might not be the case. 

I'll close my other comments. 

It might be a good idea to add a comment to the code saying that Expo generates these files so we can assume the naming pattern. As an iOS developer, this would answer questions that I would have.

2022-11-29 11:33 UTC, xtreem88 commented on src/ios/withNotificationsXcodeProject.ts
> +  for (const key in configurations) {
Yes, the code iterates through all the targets but only makes changes to the target we have created here:
```
if (
      typeof configurations[key].buildSettings !== 'undefined' &&
      configurations[key].buildSettings.PRODUCT_NAME ===
        `"${CIO_NOTIFICATION_TARGET_NAME}"`
    ) {
```

2022-11-30 14:38 UTC, levibostian commented on src/ios/withNotificationsXcodeProject.ts
> +  for (const key in configurations) {
Ohhhhhhh. I see that now.

2022-12-01 15:41 UTC, levibostian commented
@xtreem88 Why is this PR a breaking change? 

Since we are still just in `alpha`, I don't see any issues with introducing breaking changes to the code without any migration steps taken. However, I am still curious how this is a breaking change?

2022-12-02 11:48 UTC, xtreem88 commented
> @xtreem88 Why is this PR a breaking change?
> 
> Since we are still just in `alpha`, I don't see any issues with introducing breaking changes to the code without any migration steps taken. However, I am still curious how this is a breaking change?

Thanks for pointing this out. This was a mistake... I was testing the integration with `pr_lint` job, and I forgot to change this. I'll do that now.

2022-12-02 11:52 UTC, xtreem88 commented
@ami-aman @levibostian I am going to clean up this PR soon. I have been testing the changes with different Expo managed projects, and it seems to hold up well. After this, I would need another round of reviews.

2022-12-02 12:40 UTC, xtreem88 commented on src/helpers/constants/ios.ts
> +export const CIO_SDK_VERSION = '2.0.0-alpha.1';
I am updating the SDK version so that I can test it with recent versions of `customerio-reactnative`

2022-12-02 14:54 UTC, xtreem88 commented on src/helpers/constants/ios.ts
> +export const CIO_SDK_VERSION = '2.0.0-alpha.1';
@levibostian Do you think it's a good idea to leave this SDK version and ship it as is?

2022-12-06 09:04 UTC, ami-aman commented on src/helpers/constants/ios.ts
> +export const CIO_SDK_VERSION = '2.0.0-alpha.1';
Segun, is there a way to auto pull in the latest version of iOS SDK / CocoaPods ? Same for react native package version

2022-12-06 09:28 UTC, ami-aman commented on src/ios/withNotificationsXcodeProject.ts
> +    CIO_NOTIFICATION_TARGET_NAME
Same variable twice ? 🤔

2022-12-06 09:42 UTC, ami-aman commented on src/ios/withNotificationsXcodeProject.ts
> +    FileManagement.mkdir(`${iosPath}/${appName}`, {
I see this code being used at multiple places, it would be a good idea to move it to a function ?

2022-12-06 09:48 UTC, xtreem88 commented on src/ios/withNotificationsXcodeProject.ts
> +    console.warn(
This manipulates xcode project asynchronously, so at this point, the new target has not been saved; this block checks if the target already exists and then stops processing it does.

2022-12-06 09:48 UTC, ami-aman commented on src/ios/withNotificationsXcodeProject.ts
> +    CIO_NOTIFICATION_TARGET_NAME
Gotcha. How about adding a comment here to explain the same ? To me it looked like a mistake that the same property name has been passed twice.

2022-12-06 10:06 UTC, xtreem88 commented on src/ios/withNotificationsXcodeProject.ts
> +    FileManagement.mkdir(`${iosPath}/${appName}`, {
`mkdir` is already a static method in `FileManagement`

2022-12-06 13:26 UTC, Shahroz16 commented on src/ios/withNotificationsXcodeProject.ts
> +    recursive: true,
${iosPath}/${CIO_NOTIFICATION_TARGET_NAME} is being used multiple times, should we make a new const  `notificationTargetDirectory` from it and use it?

2022-12-06 15:16 UTC, levibostian requested changes
Blocking PR because the way we install versions of RN and iOS SDKs are not consistent. My PR comments address this.

2022-12-06 15:16 UTC, levibostian commented on package.json
> +    "customerio-reactnative": ">=1.0.1-alpha.3"
The version requirement should be: 
`>= 1.0.1, < 2.0` This code as it is in this PR, we will install v2 which we don't want to do. We may need to migrate our expo plugin for major versions so we don't want to install versions automatically. 

That's why I suggest: 

```suggestion
    "customerio-reactnative": "^1.0.0"
```

2022-12-06 15:16 UTC, levibostian commented on src/helpers/constants/ios.ts
> +export const CIO_SDK_VERSION = '2.0.0-alpha.1';
```suggestion
export const CIO_SDK_VERSION = '~> 2.0.0-alpha.1';
```

I like the idea of specifying the true syntax of the version string here in this constant. Instead of just the SDK version number, include the `~>` here, too. 

That does mean that we will need to update code like this in the code base: 

```
// before
export const CIO_PODFILE_SNIPPET = ` pod 'CustomerIO/MessagingPushAPN', '~> ${CIO_SDK_VERSION}'`;

// after
export const CIO_PODFILE_SNIPPET = ` pod 'CustomerIO/MessagingPushAPN', '${CIO_SDK_VERSION}'`;
```

2022-12-06 15:16 UTC, levibostian commented on src/helpers/constants/ios.ts
> +export const CIO_SDK_VERSION = '2.0.0-alpha.1';
Aman, When you say, 

> Segun, is there a way to auto pull in the latest version of iOS SDK / CocoaPods ? Same for react native package version

Are you saying the latest *minor* version of the iOS and RN SDKs? My comments in this PR thus far do that. 

When I say minor version, I am saying, `>= 1.0, <2.0` so the expo plugin doesn't automatically upgrade from v1 to v2 of an SDK. The expo plugin will install v1.3 automatically, for example, but will not install v2.0 automatically which is what we want.

2022-12-07 18:02 UTC, levibostian approved these changes

2022-12-10 08:03 UTC, merged