fix: modified regex for Expo 48 and added UNUserNotificationCenter snippet
customerio/customerio-expo-plugin pull request #82
Opened 2023-06-15 08:30 UTC by xtreem88

Resolves: https://github.com/customerio/issues/issues/10485

Details about bug and changes are on the main issue

QA instructions: https://github.com/customerio/issues/issues/10485#issuecomment-1593511370

2023-06-15 19:41 UTC, levibostian approved these changes

2023-06-15 20:07 UTC, mrehan27 approved these changes

2023-06-28 12:14 UTC, ami-aman commented on src/ios/withAppDelegateModifications.ts
> +    (match, p1, _p2, p3) => {
I am not sure if this import statements would be added to `AppDelegate.m` or `AppDelegate.h` file. It should be added to .h file.

2023-06-28 13:33 UTC, xtreem88 commented on src/ios/withAppDelegateModifications.ts
> +    (match, p1, _p2, p3) => {
It is added to `AppDelegate.h`

2023-06-28 19:40 UTC, levibostian commented on src/helpers/constants/ios.ts
> +  /(@interface AppDelegate\s:\sEXAppDelegateWrapper\s?)(<([^>]+)>)?/;
```suggestion
  /(@interface AppDelegate\s*:\s*EXAppDelegateWrapper\s*)(<([^>]+)>)?/;
```

There might be more or less whitespace characters so this suggestion could help prevent errors against that.

2023-06-28 19:40 UTC, levibostian commented on src/ios/withAppDelegateModifications.ts
> +    (match, p1, _p2, p3) => {
The comments in the function are great. 

Could you use more specific variable names instead of `match, p1, _p2, p3`? I still don't quite understand this code with those names.

2023-06-28 19:40 UTC, levibostian approved these changes

2023-06-28 19:58 UTC, levibostian requested changes
I am going to ask a couple questions in Slack. I suggest holding off on PR until you see conversation.

2023-06-30 09:33 UTC, xtreem88 commented on src/ios/withAppDelegateModifications.ts
> +      }
I am prioritizing maintainability over readability here because the snippets are basically `magic strings` I think it makes sense to have them all in one location where they can easily be changed or edited if we have to

2023-06-30 20:49 UTC, levibostian approved these changes

2023-07-14 17:45 UTC, ami-aman commented on src/ios/withAppDelegateModifications.ts
> +        props.handleNotificationClick === true
I do not think there is any direct way of assigning default values we are following in expo plugin. In case of a boolean, we can handle only one condition, either `true` or `false`. If the value of `handleNotificationClick` is not received then the plugin will not add the code otherwise it will, if `true`.

2023-08-07 10:42 UTC, merged