fix: handling deeplink in killed state
customerio/customerio-expo-plugin pull request #93
Opened 2023-07-17 14:57 UTC by ami-aman

Fixes handling deep links in killed state.

Refers : https://github.com/customerio/issues/issues/10367

2023-07-18 15:33 UTC, levibostian requested changes

2023-07-18 15:33 UTC, levibostian commented on src/helpers/constants/ios.ts
> +`;
By our Expo plugin modifying the launch options, we could make our Expo plugin become incompatible with other Expo plugins that might require `launchOptions`. 

Also, from my understanding of `RCTBridge`, the API for this code has changed a lot with different recent versions of RN. Therefore, I am not sure if this code here will be backwards compatible with multiple versions of Expo.

2023-07-18 16:28 UTC, ami-aman commented on src/ios/withAppDelegateModifications.ts
> +        stringContents = replaceCodeByRegex(stringContents, CIO_RCTBRIDGE_DEEPLINK_MODIFIEDOPTIONS_REGEX, CIO_RCTBRIDGE_DEEPLINK_MODIFIEDOPTIONS_SNIPPET);
Done ✅

2023-07-24 19:06 UTC, levibostian commented on src/helpers/constants/ios.ts
> +`;
I have been thinking about this and unfortunately, I do not have a suggestion to prevent the use of `launchOptions` or `RCTBridge`. 

I am mostly concerned with the use of `RCTBridge` and trying to make this code compatible with all versions of RN that our SDK supports. I know that you're testing against that, so I'll resolve this 👍

2023-07-28 17:07 UTC, ami-aman commented on src/helpers/constants/ios.ts
> +`;
Thanks Levi ! I have added a fix to handle compatibility for `launchOptions` or `RCTBridge`. With this fix, the code is compatible with all existing versions of Expo (>=45 & <=48) and react native !

2023-07-28 17:12 UTC, ami-aman commented on src/ios/withAppDelegateModifications.ts
> +      ) {
Thanks for the suggestion, Segun ! Please check the latest commit for the fix.

2023-08-02 10:12 UTC, Shahroz16 approved these changes

2023-08-02 10:12 UTC, mrehan27 approved these changes
LGTM

2023-08-02 10:12 UTC, mrehan27 commented on src/ios/withAppDelegateModifications.ts
> +      ) {
Isn't the following enough?

```
if (props.handleDeeplinkInKilledState === true)
```

As `undefined === true` will eventually lead to `false`

2023-08-07 08:31 UTC, ami-aman commented on src/ios/withAppDelegateModifications.ts
> +      ) {
This has been added to avoid the edge case because we do not have any direct default values of these properties.

2023-08-07 08:37 UTC, merged